{{/*
EC2NodeClass custom resource template for Karpenter v1.5.x
- Uses stable API: karpenter.k8s.aws/v1  
- Includes kubelet configuration (moved from NodePool in v1.5)
- Supports all v1.5 AWS-specific features and security options
*/}}

{{- range $key, $value := .Values.ec2NodeClass }}
{{- with $value }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ $key }}
  labels:
    {{- include "labels" $ | nindent 4 }}
  {{- if $.Values.globalAnnotations }}
  annotations:
    {{- include "annotations" $ | nindent 4 }}
  {{- end }}
spec:
  amiFamily: {{ .amiFamily | default "AL2023" }}
  {{- with .subnetSelectorTerms }}
  subnetSelectorTerms:
    {{- include "ec2NodeClass.commonSelectorTerms" . | nindent 4 }}
  {{- end }}
  {{- with .securityGroupSelectorTerms }}
  securityGroupSelectorTerms:
    {{- include "ec2NodeClass.commonSelectorTerms" . | nindent 4 }}
  {{- end }}
  {{- if .role }}
  role: {{ .role }} 
  {{- end }}
  {{- if .instanceProfile }}
  instanceProfile: {{ .instanceProfile }}
  {{- end }}
  {{- with .amiSelectorTerms }}
  amiSelectorTerms:
    {{- include "ec2NodeClass.commonSelectorTerms" . | nindent 4 }}
  {{- end }}
  {{- with .capacityReservationSelectorTerms }}
  capacityReservationSelectorTerms:
    {{- include "ec2NodeClass.commonSelectorTerms" . | nindent 4 }}
  {{- end }}
  {{- with .tags }}
  tags:                
    {{- toYaml . | nindent 4 }} 
  {{- end }}
  {{- with .metadataOptions }}
  metadataOptions:
    httpEndpoint: {{ .httpEndpoint }}
    httpProtocolIPv6: {{ .httpProtocolIPv6 }}
    httpPutResponseHopLimit: {{ .httpPutResponseHopLimit }}
    httpTokens: {{ .httpTokens }}
  {{- end }}
  {{- with .blockDeviceMappings }}
  blockDeviceMappings:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .instanceStorePolicy }}
  instanceStorePolicy: {{ . | quote }}
  {{- end }}
  {{- if .userData }} 
  userData: |
    {{- toYaml .userData | nindent 4 }}
  {{- end }}
  detailedMonitoring: {{ .detailedMonitoring | default false }}
  associatePublicIPAddress: {{ .associatePublicIPAddress | default false }}
  {{- with .kubelet }}
  kubelet:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}