{{/*
NodePool custom resource template for Karpenter v1.5.x
- Uses stable API: karpenter.sh/v1
- Kubelet configuration moved to EC2NodeClass (v1.5 requirement)
- Supports all v1.5 disruption features and budgets
*/}}

{{- range $key, $value := .Values.nodePool }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ $key }}
spec:
  template:
    metadata:
      labels:
        {{- include "nodepool.labels" $ | nindent 8 }}
        {{- with .labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .annotations $.Values.globalAnnotations }}
      annotations:
        {{- include "annotations" $ | nindent 8 }}
        {{- with .annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .nodeClassRef }}
      nodeClassRef:
        group: {{ default "karpenter.k8s.aws" .group }}
        kind: {{ default "EC2NodeClass" .kind }}
        name: {{ default "default" .name }}
      {{- end }}
      {{- with .taints }}
      taints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .startupTaints }}
      startupTaints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      expireAfter: {{ default "720h" .expireAfter | quote }}
      {{- with .terminationGracePeriod }}
      terminationGracePeriod: {{ . | quote }}
      {{- end }}
      {{- with .requirements }}
      requirements:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{/*- NOTE: In Karpenter v1.5, kubelet configuration moved to EC2NodeClass spec */}}
      {{/*- Kubelet configuration in NodePool is no longer supported */}}
  {{- if .disruption }}
  disruption: 
    {{- with .disruption }}
    consolidationPolicy: {{ default "WhenEmptyOrUnderutilized" .consolidationPolicy }}
    {{- with .consolidateAfter }}
    consolidateAfter: {{ . | quote }}
    {{- end }}
    {{- with .budgets }}
    budgets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if .limits }}
  limits:
    cpu: {{ default "100" .limits.cpu | quote }}
    memory: {{ default "100Gi" .limits.memory | quote }}
  {{- end }}
  {{- if .weight }}
  weight: {{ .weight }}
  {{- end }}
{{- end }}